currentpath: D:\workspacedemo\wenxuan.qiu\AutoTestProject\auto-test-project\tests
cycle_name: B200
framepath: Z:\code\sw_itest\tests\pytestCase
password: Njpj#04125617
testplan_key: COSSW-41721
username: wenxuan.qiu
